apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
      - name: {{ .Values.name }}
        image: ghcr.io/sakuard/tunnel-worker-controller/job-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          {{- with .Values.env }}
          {{- $secretName := .secretName }}
          {{- range $key := .keys }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secretName }}
                key: {{ $key }}
          {{- end }}
          {{- end }}
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      imagePullSecrets:
        - name: regcred