{{- with .Values.createExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
spec:
  # 這將每1分鐘刷新一次金鑰。可以根據自己的要求保留時間。
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: {{ .secretStoreRef.kind }}
  target:
    name: {{ .name }}
    creationPolicy: {{ .creationPolicy }}
  dataFrom:
    - extract:
        key: {{ .name }}
{{- end }}
