apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tunnel-manager
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: tunnel-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: tunnel-manager
  apiGroup: rbac.authorization.k8s.io
