name: Manual Helm Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'chart/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install Helm
        uses: azure/setup-helm@v4
        
      - name: Package Helm Chart
        run: |
          # 創建一個臨時目錄來存放打包的 charts
          mkdir -p .deploy
          
          # 打包 chart
          helm package chart/ -d .deploy
          
          # 生成 index.yaml
          helm repo index .deploy --url https://sakuard.github.io/tunnel-worker-controller
          
          # 檢查生成的文件
          ls -la .deploy/
          cat .deploy/index.yaml
          
      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .deploy
          keep_files: true